### ISSUE TITLE
String enums

### ISSUE THREAD

**Issue by tony** [c0m1t/relay-enum-generator#16]
It could be valuable in some cases to have [string enum](https://www.typescriptlang.org/docs/handbook/enums.html#string-enums) output:

```
export enum Phase {
  SELF_REVIEW = 'SELF_REVIEW',
  PEER_REVIEW = 'PEER_REVIEW',
  MANAGER_REVIEW = 'MANAGER_REVIEW',
  RESULTS = 'RESULTS',
  IDLE = 'IDLE',
}
```

and possibly a list of string enums:

```typescript
type PhaseType = keyof typeof Phase

const PhaseTypes: PhaseType[] = [
  SELF_REVIEW,
  PEER_REVIEW,
  MANAGER_REVIEW,
  RESULTS,
  IDLE,
]
```

^ I haven't tried the above to see if the types themselves connect, but seeing if this in general fits in scope of your project, for the moment

### Related
- https://github.com/dangcuuson/graphql-schema-typescript/issues/65
- apollo (a different, specialized tool): https://github.com/apollographql/apollo-tooling/pull/1750, https://github.com/apollographql/apollo-tooling/issues/1044

**Comment by c0m1t** [comment]
Yes it can be very helpful. I suggest you to take a look at [graphql-code-generator](https://github.com/dotansimha/graphql-code-generator). It's a great package which has got tons of options, it can generate enums as you mentioned.

**Comment by tony** [comment]
@c0m1t Thank you

Knowing that, do you think this should issue should be closed? 

Am I potentially suggesting something out of scope for your project, or is string enums something you'd like to add potentially?

**Comment by c0m1t** [comment]
As far as I remember, I created this repo because back in the day `graphql-code-generator` did not have the option to add `'%future added value'` to the types that were generated from enums. Also we wanted to generate enums once; I think  `graphql-code-generator` used to generate a type for an enum each time it was used in a file. After a while `graphql-code-generator` added those two options.

I do not have much time to add features to this package, so I cannot promise I will add this feature any time soon. But I greatly appreciate and welcome contributions to this project. So if you like to give it a shot, you can submit a pull request.

**Comment by tony** [comment]
Noted - similarly at this time, I will first look into [graphql-code-generator](https://github.com/dotansimha/graphql-code-generator), which you suggested

I am easy either way as well. I think in the mean time if someone wants to make a PR we can keep this open and it can be reviewed.

If I find that graphql-code-generator doesn't work out I will ping you here. 

In the event time passes and this goes stale and you are cleaning up issues, you can close this later on anytime.
