### ISSUE TITLE
Does this generate enums or unions?

### ISSUE THREAD

**Issue by nnthnn** [c0m1t/relay-enum-generator#5]
The package name and README seems to imply this would output enum types, but when I run this it appears to generate union types for each graphql enum. I'm not sure if the underlying packages have changed or that was your original intent.

**Comment by c0m1t** [comment]
This package generates enums as `relay-compiler` generates by default; which is as unions.
If you have a project that uses `relay`, your enum type in the generated file would be something like this:

```ts
// Component_prop.graphql.ts
export type Evaluation = "EXCEEDS_EXPECTATIONS" | "MEETS_EXPECTATIONS" | "NEEDS_IMPROVEMENT" | "SUPERB" | "%future added value";
```
Let's say there is a global `enum` named `Evaluation` which is used in different components.
Instead of importing that enum from different generated files (Cause each components which uses this enum in its query would generate this enum), it can be imported from one file.

This package was released before [graphql-code-generator](https://github.com/dotansimha/graphql-code-generator) `v1.13.4`.
In [v1.13.4](https://github.com/dotansimha/graphql-code-generator/releases/tag/v1.13.4)  they added support for `futureProofEnums` (which `relay-compiler` generates it) and `onlyOperationTypes` which generates only operation types (like enums). Those two were the main goals of this package. So now, I highly recommend you to check out their packages.   

`graphql-code-generator` gives you lots of options and you can choose how enums are generated (as `type`, `enum`, ...)

And yes, It would be a better idea to mention it explicitly that enums are generated as unions.

**Comment by nnthnn** [comment]
Thanks for the response. I'll look at `graphql-code-generator`.
